routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\BarangController;
use App\Http\Controllers\Controller;
use App\Http\Controllers\PembelianController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Route::get('/login', [AuthController::class, 'login'])->name('login');
Route::post('/login', [AuthController::class, 'authenticate'])->name('authenticate');
Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

Route::prefix('')->middleware('auth')->group(function () {
    Route::get('/dashboard', [Controller::class, 'dashboard'])->name('dashboard');
    Route::put('/user/{id}/respass', [UserController::class, 'respass'])->name('user.respass');
    Route::get('/profil', [UserController::class, 'profile'])->name('user.profile');
    Route::put('/profil', [UserController::class, 'profile_update'])->name('user.profile_update');
    Route::resource('/user', UserController::class);
    Route::resource('/barang', BarangController::class);
    Route::prefix('/pembelian')->group(function () {
        Route::redirect('/', '/pembelian/mulai');
        Route::get('/mulai', [PembelianController::class, 'start'])->name('pembelian.start');
        Route::post('/', [PembelianController::class, 'bought'])->name('pembelian.bought');
        Route::get('/riwayat', [PembelianController::class, 'history'])->name('pembelian.history');
        Route::get('/{id}/detail', [PembelianController::class, 'detail'])->name('pembelian.detail');
        Route::get('/{id}/print', [PembelianController::class, 'print'])->name('pembelian.print');
    });
});

app/Http/Controllers/BarangController.php
<?php

namespace App\Http\Controllers;

use App\Models\MasterBarang;
use App\Models\TransaksiPembelianBarang;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use RealRashid\SweetAlert\Facades\Alert;

class BarangController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        return view('barang.index', [
            'data' => MasterBarang::search()->paginate(20)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('barang.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'nama_barang' => 'required',
            'harga_satuan' => 'required'
        ]);
        
        DB::beginTransaction();
        try {
            MasterBarang::create($validated);
        } catch (\Exception $e) {
            DB::rollback();
            throw $e;
        }
        DB::commit();
        
        Alert::success('Berhasil!', 'Data barang berhasil dibuat!');
        return redirect(route('barang.index'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('barang.edit', [
            'data' => MasterBarang::find($id)
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validated = $request->validate([
            'nama_barang' => 'required',
            'harga_satuan' => 'required'
        ]);
        
        DB::beginTransaction();
        try {
            MasterBarang::where('id', $id)->update($validated);
        } catch (\Exception $e) {
            DB::rollback();
            throw $e;
        }
        DB::commit();
        
        Alert::success('Berhasil!', 'Data barang berhasil diupdate!');
        return redirect(route('barang.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $check = TransaksiPembelianBarang::where('master_barang_id', $id)->first();
        if ($check !== NULL) {
            Alert::error('Gagal!', 'Data barang tidak dapat dihapus karena telah tercatat dalam transaksi!')->width(700);
            return redirect(route('barang.index'));
        }
        DB::beginTransaction();
        try {
            MasterBarang::destroy($id);
        } catch (\Exception $e) {
            DB::rollback();
            throw $e;
        }
        DB::commit();

        Alert::success('Berhasil!', 'Data barang berhasil dihapus!');
        return redirect(route('barang.index'));
    }
}

resources/views/barang/create.blade.php
@extends('layouts.template')
@section('title', 'Tambah Data Barang')
@section('content')
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Tambah Data Barang</h4>
            </div>
            <div class="card-body">
                <form action="{{ route('barang.store') }}" method="post" class="form-horizontal" id="form-create">
                    @csrf
                    <div class="form-group row">
                        <label class="col-lg-2 col-form-label">Nama Barang :</label>
                        <div class="col-lg-4">
                            <input type="text" class="form-control" name="nama_barang" maxlength="50" placeholder="Nama Barang" autocomplete="off" required value="{{ old('nama_barang') }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-lg-2 col-form-label">Harga Satuan :</label>
                        <div class="col-lg-4">
                            <input type="text" class="form-control" name="harga_satuan" id="harga_satuan" placeholder="Harga Satuan" autocomplete="off" required value="{{ old('harga_satuan') }}" onkeyup="formatRupiah(this.id)">
                        </div>
                    </div>
                    <div class="text-right mt-1">
                        <a href="{{ route('barang.index') }}" class="btn btn-secondary btn-icon-split">
                            <span class="icon text-white-50">
                                <i class="fas fa-arrow-left"></i>
                            </span>
                            <span class="text">Kembali</span>
                        </a>
                        <button type="submit" class="btn btn-success btn-icon-split" id="btn-submit" form="form-create">
                            <span class="icon text-white-50">
                                <i class="fas fa-save"></i>
                            </span>
                            <span class="text">Simpan</span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
        @if ($errors->any())
            <div class="card mt-2">
                <div class="card-body">
                    <h5>Terdapat kesalahan: </h5>
                    <div class="text-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
        @endif
    </div>
@endsection

@push('script')
    <script>
        $('#form-create').on('submit', function () {
            let raw = $('input[name=harga_satuan]').val();
            let formatted = raw.replace(/rp|[.]/gi, "");
            $('input[name=harga_satuan]').val(formatted);
        });
        function formatRupiah(id) {
            let angka = document.getElementById(id).value;
            let number_string = angka.replace(/[^,\d]/g, '').toString(),
                split = number_string.split(','),
                sisa = split[0].length % 3,
                rupiah = split[0].substr(0, sisa),
                ribuan = split[0].substr(sisa).match(/\d{3}/gi);

            if (ribuan) {
                separator = sisa ? '.' : '';
                rupiah += separator + ribuan.join('.');
            }

            rupiah = split[1] != undefined ? rupiah + ',' + split[1] : rupiah;
            document.getElementById(id).value = 'Rp' + rupiah;
        }
    </script>
@endpush

resources/views/barang/edit.blade.php
@extends('layouts.template')
@section('title', 'Edit Data Barang')
@section('content')
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-lg-7">
                        <h4 class="card-title">Edit Data Barang</h4>
                    </div>
                    <div class="col-lg-5">
                        <div class="text-right">
                            <a href="{{ route('barang.index') }}" class="btn btn-secondary btn-icon-split">
                                <span class="icon text-white-50">
                                    <i class="fas fa-arrow-left"></i>
                                </span>
                                <span class="text">Kembali</span>
                            </a>
                            <button type="button" class="btn btn-warning btn-icon-split" id="btn-edit">
                                <span class="icon text-white-50">
                                    <i class="fas fa-edit"></i>
                                </span>
                                <span class="text">Edit</span>
                            </button>
                            <button type="button" class="btn btn-danger btn-icon-split" id="btn-reset" style="display: none">
                                <span class="icon text-white-50">
                                    <i class="fas fa-times"></i>
                                </span>
                                <span class="text">Reset</span>
                            </button>
                            <button type="submit" class="btn btn-success btn-icon-split" id="btn-submit" form="form-update" disabled>
                                <span class="icon text-white-50">
                                    <i class="fas fa-save"></i>
                                </span>
                                <span class="text">Simpan</span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <form action="{{ route('barang.update', [$data->id]) }}" method="post" class="form-horizontal" id="form-update">
                    @csrf
                    @method('PUT')
                    <div class="form-group row">
                        <label class="col-lg-2 col-form-label">Nama Barang :</label>
                        <div class="col-lg-4">
                            <input type="text" class="form-control" name="nama_barang" maxlength="50" placeholder="Nama Barang" autocomplete="off" required value="{{ $data->nama_barang }}" readonly>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-lg-2 col-form-label">Harga Satuan :</label>
                        <div class="col-lg-4">
                            <input type="text" class="form-control" name="harga_satuan" id="harga_satuan" placeholder="Harga Satuan" autocomplete="off" required value="{{ formatRupiah($data->harga_satuan, 0) }}" onkeyup="formatRupiah(this.id)" readonly>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        @if ($errors->any())
            <div class="card mt-2">
                <div class="card-body">
                    <h5>Terdapat kesalahan: </h5>
                    <div class="text-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
        @endif
    </div>
@endsection

@push('script')
    <script>
        $(document).ready(function (){
            $('#btn-edit').on('click', function () {
                $("input[name=nama_barang]").attr('readonly', false);
                $("input[name=harga_satuan]").attr('readonly', false);
                $('#btn-edit').hide();
                $('#btn-reset').show();
                $('#btn-submit').attr('disabled', false);
            });
            $('#btn-reset').on('click', function () {
                $("input[name=nama_barang]").attr('readonly', true);
                $("input[name=harga_satuan]").attr('readonly', true);
                $("input[name=nama_barang]").val('{{ $data->nama_barang }}');
                $("input[name=harga_satuan]").val('{{ formatRupiah($data->harga_satuan, 0) }}');
                $('#btn-reset').hide();
                $('#btn-edit').show();
                $('#btn-submit').attr('disabled', true);
            });

            $('#form-update').on('submit', function () {
                let raw = $('input[name=harga_satuan]').val();
                let formatted = raw.replace(/rp|[.]/gi, "");
                $('input[name=harga_satuan]').val(formatted);
            });
        });

        function formatRupiah(id) {
            let angka = document.getElementById(id).value;
            let number_string = angka.replace(/[^,\d]/g, '').toString(),
                split = number_string.split(','),
                sisa = split[0].length % 3,
                rupiah = split[0].substr(0, sisa),
                ribuan = split[0].substr(sisa).match(/\d{3}/gi);

            if (ribuan) {
                separator = sisa ? '.' : '';
                rupiah += separator + ribuan.join('.');
            }

            rupiah = split[1] != undefined ? rupiah + ',' + split[1] : rupiah;
            document.getElementById(id).value = 'Rp' + rupiah;
        }
    </script>
@endpush

resources/views/barang/index.blade.php
@extends('layouts.template')
@section('title', 'Data Barang')
@push('style')
<!-- SweetAlert -->
    <link rel="stylesheet" href="{{ asset('plugins/sweetalert2/css/sweetalert2.min.css')}}">
    <style>
        input[type=number]::-webkit-outer-spin-button,
        input[type=number]::-webkit-inner-spin-button {
            -webkit-appearance: none;
            margin: 0;
        }

        input[type=number] {
            -moz-appearance:textfield;
        }
    </style>
@endpush

@section('content')
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Data Barang</h4>
            </div>
            <div class="card-body">
                <div class="row mb-3">
                    <div class="col-lg-12">
                        <a href="{{ route('barang.create') }}" class="btn btn-primary btn-icon-split mr-1"
                            data-toggle="tooltip" data-placement="top" title="Tambah Data Barang">
                            <span class="icon text-white-50">
                                <i class="fas fa-plus"></i> 
                            </span>
                            <span class="text">Tambah Data</span>
                        </a>
                        <span data-toggle="modal" data-target="#modalFilter">
                            <a class="btn btn-info btn-icon-split mr-1" 
                                data-toggle="tooltip" data-placement="top" title="Filter Data Barang">
                                <span class="icon text-white-50">
                                    <i class="fas fa-filter"></i> 
                                </span>
                                <span class="text">Filter</span>
                            </a>
                        </span>
                        @if (request('nama') || request('harga'))
                            <a href="{{ route('barang.index') }}" class="btn btn-danger btn-icon-split mr-1"
                                data-toggle="tooltip" data-placement="top" title="Bersihkan Filter">
                                <span class="icon text-white-50">
                                    <i class="fas fa-broom"></i> 
                                </span>
                                <span class="text">Bersihkan Filter</span>
                            </a>
                        @endif
                    </div>
                </div>
                @if (request('nama') || request('harga'))
                    <p class="text-secondary">
                        Filter saat ini : <br>
                        {!! request('nama') ? '&emsp;&emsp; Nama Barang : ' . request('nama') . '<br>' : '' !!}
                        {!! request('harga') ? '&emsp;&emsp; Harga Satuan : ' . (request('op') == 'lt' ? 'Kurang dari ' : (request('op') == 'gt' ? 'Lebih dari ' : 'Sama dengan ')) . formatRupiah(request('harga'), 0) . '<br>' : '' !!}
                    </p>
                @endif
                @if ($data->count())
                    <div class="table-responsive">
                        <table class="table table-bordered table-hover" id="table-user">
                            <thead>
                                <tr role="row" style="background-color:#dadada">
                                    <th class="text-center" style="width: 5%;">No</th>
                                    <th>Nama Barang</th>
                                    <th class="text-right">Harga Satuan</th>
                                    <th class="text-center" style="width: 15%;"><i class="fas fa-cog"></i></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($data as $item)
                                <tr>
                                    <td>{{ (($data->currentPage() - 1) * $data->perPage()) + $loop->iteration }}</td>
                                    <td>{{ $item->nama_barang }}</td>
                                    <td class="text-right">{{ formatRupiah($item->harga_satuan, 0) }}</td>
                                    <td class="text-center">
                                        <a href="{{ route('barang.edit', [$item->id]) }}"
                                            class="btn btn-sm btn-warning btn-action mx-1" data-container="table"
                                            data-toggle="tooltip" data-placement="top" title="Edit Data Barang">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                        <form action="{{ route('barang.destroy', [$item->id]) }}" method="POST"
                                            id="form-delete-{{$item->id}}" style="display: inline">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger btn-sm"
                                                onclick="submit_delete({{$item->id}})" data-container="table"
                                                data-toggle="tooltip" data-placement="top" title="Hapus Data Barang">
                                                <i class="far fa-trash-alt"></i>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="d-flex justify-content-center mt-3">
                        {!! $data->links() !!}
                    </div>
                @else
                    <div class="text-center">
                        <h3>Tidak ada data ditemukan.</h3>
                        <img src="{{ asset('img/data_empty.jpg') }}" width="427px" height="240px">
                    </div>
                @endif
            </div>
        </div>
    </div>

    <div class="modal fade" id="modalFilter" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Filter Data</h5>
                    <button class="close" type="button" data-dismiss="modal">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{ route('barang.index') }}" class="form-horizontal" id="form-filter">
                        <div class="text-secondary small mb-2">Filter dapat diisi semua atau hanya salah satunya.</div>
                        <div class="form-group row">
                            <label class="col-lg-4 col-form-label">Perbandingan Harga :</label>
                            <div class="col-lg-8">
                                <select class="form-control" name="op">
                                    <option value="" disabled selected>--Pilih salah satu--</option>
                                    <option value="lt">Kurang dari</option>
                                    <option value="gt">Lebih dari</option>
                                    <option value="eq">Sama dengan</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-lg-4 col-form-label">Harga Satuan :</label>
                            <div class="col-lg-8">
                                <input type="number" class="form-control" name="harga" placeholder="Harga Satuan" autocomplete="off">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-lg-4 col-form-label">Nama Barang :</label>
                            <div class="col-lg-8">
                                <input type="text" class="form-control" name="nama" maxlength="50" placeholder="Nama Barang" autocomplete="off">
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Batal</button>
                    <input class="btn btn-success" type="submit" value="Filter" form="form-filter">
                </div>
            </div>
        </div>
    </div>
@endsection

@push('script')
<!-- Script Tambahan -->
    <script src="{{ asset('plugins/sweetalert2/js/sweetalert2.all.min.js') }}"></script>
    <script type="text/javascript">
        $('[data-toggle="tooltip"]').tooltip();
        $('input[name=harga]').on('keyup', function () {
            $('input[name=harga]').val() != '' ? $('select[name=op]').prop('required', true) : $('select[name=op]').prop('required', false)
        });
        $('select[name=op]').on('change', function () {
            $('input[name=harga]').prop('required', true);
        });
        $('#form-filter').on('submit', function () {
            $('input[name=nama]').val() == '' ? $('input[name=nama]').removeAttr('name') : false;
            $('input[name=harga]').val() == '' ? $('input[name=harga]').removeAttr('name') : false;
        });
        
        function submit_delete(user_id) {
            event.preventDefault();
            Swal.fire({
                width: 680,
                title: 'Anda yakin ingin menghapus data terpilih?',
                text: "Data yang sudah di hapus tidak bisa dikembalikan!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Hapus',
                cancelButtonText: 'Tidak'
            }).then((result) => {
                if (result.value == true) {
                    $(`#form-delete-${user_id}`).submit();
                } else {
                    return false;
                }
            });
        }
    </script>
@endpush