routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\BarangController;
use App\Http\Controllers\Controller;
use App\Http\Controllers\PembelianController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Route::get('/login', [AuthController::class, 'login'])->name('login');
Route::post('/login', [AuthController::class, 'authenticate'])->name('authenticate');
Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

Route::prefix('')->middleware('auth')->group(function () {
    Route::get('/dashboard', [Controller::class, 'dashboard'])->name('dashboard');
    Route::put('/user/{id}/respass', [UserController::class, 'respass'])->name('user.respass');
    Route::get('/profil', [UserController::class, 'profile'])->name('user.profile');
    Route::put('/profil', [UserController::class, 'profile_update'])->name('user.profile_update');
    Route::resource('/user', UserController::class);
    Route::resource('/barang', BarangController::class);
    Route::prefix('/pembelian')->group(function () {
        Route::redirect('/', '/pembelian/mulai');
        Route::get('/mulai', [PembelianController::class, 'start'])->name('pembelian.start');
        Route::post('/', [PembelianController::class, 'bought'])->name('pembelian.bought');
        Route::get('/riwayat', [PembelianController::class, 'history'])->name('pembelian.history');
        Route::get('/{id}/detail', [PembelianController::class, 'detail'])->name('pembelian.detail');
        Route::get('/{id}/print', [PembelianController::class, 'print'])->name('pembelian.print');
    });
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $table = 'users';
    protected $fillable = [
        'name',
        'username',
        'email',
        'password',
        'role_id',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
    ];

    protected $guarded = [
        'id'
    ];

    public function role()
    {
        return $this->belongsTo(Role::class, 'role_id');
    }

    public function user()
    {
        return $this->hasMany(TransaksiPembelian::class, 'id');
    }

    public function scopeSearch($query)
    {
        if (request('role'))
        {
            $query->whereHas('role', function ($query) {
                return $query->where('name', ucfirst(request('role')));
            });
        }
        if (request('username'))
        {
            $query->where('username', 'like', '%' . request('username') . '%');
        }
        if (request('email'))
        {
            $query->where('email', 'like', '%' . request('email') . '%');
        }
        return $query;
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use App\Models\TransaksiPembelian;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Redis;
use RealRashid\SweetAlert\Facades\Alert;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if(Auth::user()->role_id == 1) {
            return view('user.index', [
                'data' => User::search()->paginate(20)
            ]);
        }
        else {
            Alert::error('Unauthorized!', 'Anda tidak diperkenankan untuk mengakses halaman in!');
            return redirect()->back();
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(Auth::user()->role_id == 1) {
            return view('user.create');
        }
        else {
            Alert::error('Unauthorized!', 'Anda tidak diperkenankan untuk mengakses halaman in!');
            return redirect()->back();
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if(Auth::user()->role_id == 1) {
            $validated = $request->validate([
                'name' => 'required|alpha_spaces',
                'username' => 'required|alpha_num|unique:users,username',
                'email' => 'required|email|unique:users,email',
                'role_id' => 'required'
            ]);
            $validated['password'] = Hash::make('kasirku');

            DB::beginTransaction();
            try {
                User::create($validated);
            } catch (\Exception $e) {
                DB::rollback();
                throw $e;
            }
            DB::commit();
            
            Alert::success('Berhasil!', 'Data kasir berhasil dibuat!');
            return redirect(route('user.index'));
        }
        else {
            Alert::error('Unauthorized!', 'Anda tidak diperkenankan untuk mengakses halaman in!');
            return redirect()->back();
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(Auth::user()->role_id == 1) {
            return view('user.edit', [
                'data' => User::find($id)
            ]);
        }
        else {
            Alert::error('Unauthorized!', 'Anda tidak diperkenankan untuk mengakses halaman in!');
            return redirect()->back();
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if(Auth::user()->role_id == 1) {
            $validated = $request->validate([
                'name' => 'required|alpha_spaces',
                'username' => 'required|alpha_num|unique:users,username,'. $id . ',id',
                'email' => 'required|email|unique:users,email,'. $id . ',id',
                'role_id' => 'required',
            ]);

            DB::beginTransaction();
            try {
                User::where('id', $id)->update($validated);
            } catch (\Exception $e) {
                DB::rollback();
                throw $e;
            }
            DB::commit();
            
            Alert::success('Berhasil!', 'Data kasir berhasil diupdate!');
            return redirect(route('user.index'));
        }
        else {
            Alert::error('Unauthorized!', 'Anda tidak diperkenankan untuk mengakses halaman in!');
            return redirect()->back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(Auth::user()->role_id == 1) {
            $check = TransaksiPembelian::where('user_id', $id)->first();
            if ($check !== NULL) {
                Alert::error('Gagal!', 'Data kasir tidak dapat dihapus karena telah tercatat dalam transaksi!')->width(700);
                return redirect(route('user.index'));
            }
            DB::beginTransaction();
            try {
                User::destroy($id);
            } catch (\Exception $e) {
                DB::rollback();
                throw $e;
            }
            DB::commit();

            Alert::success('Berhasil!', 'Data kasir berhasil dihapus!');
            return redirect(route('user.index'));
        }
        else {
            Alert::error('Unauthorized!', 'Anda tidak diperkenankan untuk mengakses halaman in!');
            return redirect()->back();
        }
    }

    public function respass($id)
    {
        if(Auth::user()->role_id == 1) {
            DB::beginTransaction();
            try {
                User::where('id', $id)->update(['password' => Hash::make('kasirku')]);
            } catch (\Exception $e) {
                DB::rollback();
                throw $e;
            }
            DB::commit();
            
            Alert::success('Berhasil!', 'Password kasir terpilih berhasil direset!');
            return redirect(route('user.index'));
        }
        else {
            Alert::error('Unauthorized!', 'Anda tidak diperkenankan untuk mengakses halaman in!');
            return redirect()->back();
        }
    }

    public function profile()
    {
        return view('user.profile', [
            'data' => User::find(Auth::user()->id)
        ]);
    }

    public function profile_update(Request $request)
    {
        $id = Auth::user()->id;
        $validated = $request->validate([
            'name' => 'required|alpha_spaces',
            'username' => 'required|alpha_num|unique:users,username,'. $id . ',id',
            'email' => 'required|email|unique:users,email,'. $id . ',id',
        ]);

        if($request->password) {
            $validated['password'] = Hash::make($request->password);
        }

        DB::beginTransaction();
        try {
            User::where('id', $id)->update($validated);
        } catch (\Exception $e) {
            DB::rollback();
            throw $e;
        }
        DB::commit();
        
        Alert::success('Berhasil!', 'Profil berhasil diupdate!');
        return redirect(route('user.profile'));
    }
}

resources/views/user/create.blade.php
@extends('layouts.template')
@section('title', 'Tambah Data Kasir')
@section('content')
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Tambah Data Kasir</h4>
            </div>
            <div class="card-body">
                <form action="{{ route('user.store') }}" method="post" class="form-horizontal" id="form-create">
                    @csrf
                    <div class="form-group row">
                        <label class="col-lg-2 col-form-label">Nama Kasir :</label>
                        <div class="col-lg-4">
                            <input type="text" class="form-control" name="name" maxlength="100" placeholder="Nama Kasir" autocomplete="off" required value="{{ old('name') }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-lg-2 col-form-label">Username :</label>
                        <div class="col-lg-4">
                            <input type="text" class="form-control" name="username" maxlength="50" placeholder="Username" autocomplete="off" required value="{{ old('username') }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-lg-2 col-form-label">Email :</label>
                        <div class="col-lg-4">
                            <input type="text" class="form-control" name="email" maxlength="50" placeholder="Email" autocomplete="off" required value="{{ old('email') }}">
                        </div>
                    </div>
                    <div class="form-group row">
                    <label class="col-lg-2 col-form-label">Role :</label>
                        <div class="col-lg-4">
                            <select class="form-control" name="role_id">
                                <option value="" disabled selected>--Pilih salah satu--</option>
                                <option value="1">Admin</option>
                                <option value="2">Kasir</option>
                            </select>
                        </div>
                    </div>
                    <small class="text-secondary">Password user kasir akan dibuatkan secara default yaitu "kasirku", beritahu user untuk mengubah password setelah akun terbuat pada menu profil!</small>
                    <div class="text-right mt-1">
                        <a href="{{ route('user.index') }}" class="btn btn-secondary btn-icon-split">
                            <span class="icon text-white-50">
                                <i class="fas fa-arrow-left"></i>
                            </span>
                            <span class="text">Kembali</span>
                        </a>
                        <button type="submit" class="btn btn-success btn-icon-split" id="btn-submit" form="form-create">
                            <span class="icon text-white-50">
                                <i class="fas fa-save"></i>
                            </span>
                            <span class="text">Simpan</span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
        @if ($errors->any())
            <div class="card mt-2">
                <div class="card-body">
                    <h5>Terdapat kesalahan: </h5>
                    <div class="text-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
        @endif
    </div>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.template')
@section('title', 'Edit Data Kasir')
@section('content')
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-lg-7">
                        <h4 class="card-title">Edit Data Kasir</h4>
                    </div>
                    <div class="col-lg-5">
                        <div class="text-right">
                            <a href="{{ route('user.index') }}" class="btn btn-secondary btn-icon-split">
                                <span class="icon text-white-50">
                                    <i class="fas fa-arrow-left"></i>
                                </span>
                                <span class="text">Kembali</span>
                            </a>
                            <button type="button" class="btn btn-warning btn-icon-split" id="btn-edit">
                                <span class="icon text-white-50">
                                    <i class="fas fa-edit"></i>
                                </span>
                                <span class="text">Edit</span>
                            </button>
                            <button type="button" class="btn btn-danger btn-icon-split" id="btn-reset" style="display: none">
                                <span class="icon text-white-50">
                                    <i class="fas fa-times"></i>
                                </span>
                                <span class="text">Reset</span>
                            </button>
                            <button type="submit" class="btn btn-success btn-icon-split" id="btn-submit" form="form-update" disabled>
                                <span class="icon text-white-50">
                                    <i class="fas fa-save"></i>
                                </span>
                                <span class="text">Simpan</span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <form action="{{ route('user.update', [$data->id]) }}" method="post" class="form-horizontal" id="form-update">
                    @csrf
                    @method('PUT')
                    <div class="form-group row">
                        <label class="col-lg-2 col-form-label">Nama Kasir :</label>
                        <div class="col-lg-4">
                            <input type="text" class="form-control" name="name" maxlength="100" placeholder="Nama Kasir" autocomplete="off" required value="{{ $data->name }}" readonly>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-lg-2 col-form-label">Username :</label>
                        <div class="col-lg-4">
                            <input type="text" class="form-control" name="username" maxlength="50" placeholder="Username" autocomplete="off" required value="{{ $data->username }}" readonly>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-lg-2 col-form-label">Email :</label>
                        <div class="col-lg-4">
                            <input type="text" class="form-control" name="email" maxlength="50" placeholder="Email" autocomplete="off" required value="{{ $data->email }}" readonly>
                        </div>
                    </div>
                    <div class="form-group row">
                    <label class="col-lg-2 col-form-label">Role :</label>
                        <div class="col-lg-4">
                            <select class="form-control" name="role_id" disabled>
                                <option value="1" {{ $data->role_id == 1 ? 'selected' : '' }}>Admin</option>
                                <option value="2" {{ $data->role_id == 2 ? 'selected' : '' }}>Kasir</option>
                            </select>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        @if ($errors->any())
            <div class="card mt-2">
                <div class="card-body">
                    <h5>Terdapat kesalahan: </h5>
                    <div class="text-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
        @endif
    </div>
@endsection

@push('script')
    <script>
        $(document).ready(function (){
            $('#btn-edit').on('click', function () {
                $("input[name=name]").attr('readonly', false);
                $("input[name=username]").attr('readonly', false);
                $("input[name=email]").attr('readonly', false);
                $("select[name=role_id]").attr('disabled', false);
                $('#btn-edit').hide();
                $('#btn-reset').show();
                $('#btn-submit').attr('disabled', false);
            });
            $('#btn-reset').on('click', function () {
                $("input[name=name]").attr('readonly', true);
                $("input[name=username]").attr('readonly', true);
                $("input[name=email]").attr('readonly', true);
                $("select[name=role_id]").attr('disabled', true);
                $("input[name=name]").val('{{ $data->name }}');
                $("input[name=username]").val('{{ $data->username }}');
                $("input[name=email]").val('{{ $data->email }}');
                $("select[name=role_id]").val('{{ $data->role_id }}').change();
                $('#btn-reset').hide();
                $('#btn-edit').show();
                $('#btn-submit').attr('disabled', true);
            });
        });
    </script>
@endpush

resources/views/user/profile.blade.php
@extends('layouts.template')
@section('title', 'Profil')
@section('content')
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-lg-7">
                        <h4 class="card-title">Profil</h4>
                    </div>
                    <div class="col-lg-5">
                        <div class="text-right">
                            <button type="button" class="btn btn-warning btn-icon-split" id="btn-edit">
                                <span class="icon text-white-50">
                                    <i class="fas fa-edit"></i>
                                </span>
                                <span class="text">Edit</span>
                            </button>
                            <button type="button" class="btn btn-danger btn-icon-split" id="btn-reset" style="display: none">
                                <span class="icon text-white-50">
                                    <i class="fas fa-times"></i>
                                </span>
                                <span class="text">Reset</span>
                            </button>
                            <button type="submit" class="btn btn-success btn-icon-split" id="btn-submit" form="form-update" disabled>
                                <span class="icon text-white-50">
                                    <i class="fas fa-save"></i>
                                </span>
                                <span class="text">Simpan</span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <form action="{{ route('user.profile_update')}}" method="post" class="form-horizontal" id="form-update">
                    @csrf
                    @method('PUT')
                    <div class="form-group row">
                        <label class="col-lg-2 col-form-label">Nama Kasir :</label>
                        <div class="col-lg-4">
                            <input type="text" class="form-control" name="name" maxlength="100" placeholder="Nama Kasir" autocomplete="off" required value="{{ $data->name }}" readonly>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-lg-2 col-form-label">Username :</label>
                        <div class="col-lg-4">
                            <input type="text" class="form-control" name="username" maxlength="50" placeholder="Username" autocomplete="off" required value="{{ $data->username }}" readonly>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-lg-2 col-form-label">Email :</label>
                        <div class="col-lg-4">
                            <input type="text" class="form-control" name="email" maxlength="50" placeholder="Email" autocomplete="off" required value="{{ $data->email }}" readonly>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-lg-2 col-form-label">Password :</label>
                        <div class="col-lg-4">
                            <input type="password" class="form-control" name="password" maxlength="50" placeholder="Password" autocomplete="off" readonly>
                            <small class="text-secondary">Kosongkan password jika tidak ingin mengubahnya.</small>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        @if ($errors->any())
            <div class="card mt-2">
                <div class="card-body">
                    <h5>Terdapat kesalahan: </h5>
                    <div class="text-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
        @endif
    </div>
@endsection

@push('script')
    <script>
        $(document).ready(function (){
            $('#btn-edit').on('click', function () {
                $("input[name=name]").attr('readonly', false);
                $("input[name=username]").attr('readonly', false);
                $("input[name=email]").attr('readonly', false);
                $("input[name=password]").attr('readonly', false);
                $('#btn-edit').hide();
                $('#btn-reset').show();
                $('#btn-submit').attr('disabled', false);
            });
            $('#btn-reset').on('click', function () {
                $("input[name=name]").attr('readonly', true);
                $("input[name=username]").attr('readonly', true);
                $("input[name=email]").attr('readonly', true);
                $("input[name=password]").attr('readonly', true);
                $("input[name=name]").val('{{ $data->name }}');
                $("input[name=username]").val('{{ $data->username }}');
                $("input[name=email]").val('{{ $data->email }}');
                $('#btn-reset').hide();
                $('#btn-edit').show();
                $('#btn-submit').attr('disabled', true);
            });
        });
    </script>
@endpush